name: "Protos-Windows Test"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run test
        shell: bash
        run: |
          ruby --version && gem install google-protobuf-3.15.8.gem && ruby -w protos-windows.rb
